language: php

php:
    - '7.2'
    - '7.3'

#services:
#    - mysql

before_script:
    - composer install
#    - mysql -e 'create database dsql_test;'

after_script:
    - echo $TRAVIS_PHP_VERSION
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then echo "Sending coverage report"; vendor/bin/test-reporter; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then echo "Sending codecov report"; bash <(curl -s https://codecov.io/bash); fi

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.3" ]]; then NC="--no-coverage"; fi
    - ./vendor/phpunit/phpunit/phpunit $NC

cache:
  directories:
    - $HOME/.composer/cache

notifications:
    slack:
        rooms:
            - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
        on_success: change

    urls:
      - https://webhooks.gitter.im/e/b33a2db0c636f34bafa9

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

    email: false
