ignore:
  - demos
  - docs
  - template
  - tests
  - tests-behat
comment: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1
    patch: false
    changes: false
